export const players = [
    {
        "steamId": "76561199093444412",
        "displayName": "ducks in person",
        "avatar": "https://avatars.fastly.steamstatic.com/cdd9fbcdce8d10d647986587c968af9a19b824e8_full.jpg",
        "profileurl": "https://steamcommunity.com/id/TheDuckxd/",
        "match": "13",
        "elo": 380,
        "points": 0,
        "damage": 16296,
        "kills": 1,
        "win": 10,
        "losser": "6",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": true,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": true,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199153288700",
        "displayName": "ERES MIA",
        "avatar": "https://avatars.fastly.steamstatic.com/1185c125e94db73e635c9678f8ee820ced2fabcd_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199153288700",
        "match": "13",
        "elo": 410,
        "points": 0,
        "damage": 9659,
        "kills": 2,
        "win": 9,
        "losser": "4",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199118824281",
        "displayName": "un causa mas PP15",
        "avatar": "https://avatars.fastly.steamstatic.com/34654b9fbc7efbddae83bccf493f5dbbccf2128b_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199118824281",
        "match": "11",
        "elo": 375,
        "points": 0,
        "damage": 9557,
        "kills": 5,
        "win": 10,
        "losser": "2",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561198361277623",
        "displayName": "P DIDDY",
        "avatar": "https://avatars.fastly.steamstatic.com/7b46c3884a4c84b6d6c1dbe3ea448c967aaab7b6_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561198361277623",
        "match": "9",
        "elo": 345,
        "points": 0,
        "damage": 5367,
        "kills": 0,
        "win": 4,
        "losser": "3",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199164549325",
        "displayName": "ETI A LA CASA",
        "avatar": "https://avatars.fastly.steamstatic.com/84be9c104665c40f47d3cfb62d9bdb37ac666eb4_full.jpg",
        "profileurl": "https://avatars.fastly.steamstatic.com/84be9c104665c40f47d3cfb62d9bdb37ac666eb4_full.jpg",
        "match": "5",
        "elo": 330,
        "points": 0,
        "damage": 1804,
        "kills": 0,
        "win": 2,
        "losser": "4",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199629243648",
        "displayName": "RHLM1447",
        "avatar": "https://avatars.fastly.steamstatic.com/a02f8682811d97828cf682bd046cfcdab53258ee_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199629243648",
        "match": "11",
        "elo": 330,
        "points": 0,
        "damage": 9356,
        "kills": 0,
        "win": 3,
        "losser": "6",
        "draw": "1",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199551960335",
        "displayName": "OSI NENA",
        "avatar": "https://avatars.fastly.steamstatic.com/7aa0011089f29c548a8ca3c241fdc4c10f79b878_full.jpg",
        "profileurl": "https://steamcommunity.com/id/psyk3s07",
        "match": "11",
        "elo": 330,
        "points": 0,
        "damage": 9434,
        "kills": 1,
        "win": 2,
        "losser": "8",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199153842229",
        "displayName": "HeiSenBerG",
        "avatar": "https://avatars.fastly.steamstatic.com/104d981daad5e730619fbb5d885a2a712f2feaf1_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199153842229/",
        "match": "5",
        "elo": 330,
        "points": 0,
        "damage": 1000,
        "kills": 0,
        "win": 5,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199502583075",
        "displayName": "Cypez",
        "avatar": "https://avatars.fastly.steamstatic.com/cf09c47c3403476f697b504d74cef42be73daa29_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199502583075/",
        "match": "3",
        "elo": 330,
        "points": 0,
        "damage": 4487,
        "kills": 0,
        "win": 2,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199553792162",
        "displayName": "Cazavenecas",
        "avatar": "https://avatars.fastly.steamstatic.com/e182ac1e5fb39ebe199b48d570b7b9061c8d9730_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199553792162/",
        "match": "3",
        "elo": 330,
        "points": 0,
        "damage": 2000,
        "kills": 0,
        "win": 2,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199857774654",
        "displayName": "Tyrone_TuseadorRevolucionario",
        "avatar": "https://avatars.fastly.steamstatic.com/ecfe86789c66e379fa340fe8c57a55abe09eed86_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199857774654",
        "match": "8",
        "elo": 325,
        "points": 0,
        "damage": 8177,
        "kills": 0,
        "win": 2,
        "losser": "6",
        "draw": "1",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": false,
        "__v": 0
    },
    {
        "steamId": "76561199093672155",
        "displayName": "Papadrilo",
        "avatar": "https://avatars.fastly.steamstatic.com/f5342ccb179f561db4af68ee229b58ba6c518b17_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199093672155",
        "match": "1",
        "elo": 315,
        "points": 0,
        "damage": 1000,
        "kills": 0,
        "win": 1,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199223923610",
        "displayName": "Lino",
        "avatar": "https://avatars.fastly.steamstatic.com/5140281335d8176482a0191d8edc233da2ecc633_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199223923610",
        "match": "1",
        "elo": 315,
        "points": 0,
        "damage": 1000,
        "kills": 0,
        "win": 1,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561199023262589",
        "displayName": "Yami",
        "avatar": "https://avatars.fastly.steamstatic.com/863fa87bc7178d879367b60e10c91a984c2d0c3a_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561199023262589/",
        "match": "0",
        "elo": 300,
        "points": 0,
        "damage": 0,
        "kills": 0,
        "win": 0,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    },
    {
        "steamId": "76561198998575258",
        "displayName": "mangodictador",
        "avatar": "https://avatars.fastly.steamstatic.com/7a741b8d9d4b80e71571ba1bdb1d4fd8814f740d_full.jpg",
        "profileurl": "https://steamcommunity.com/profiles/76561198998575258",
        "match": "0",
        "elo": 300,
        "points": 0,
        "damage": 0,
        "kills": 0,
        "win": 0,
        "losser": "0",
        "draw": "0",
        "rank": "Bronze",
        "lastMatches": ["N", "N", "N", "N", "N"],
        "fg_championsbulls": false,
        "playoff": false,
        "fg_marquez_league": false,
        "descenso": false,
        "isAdmin": false,
        "active": true,
        "__v": 0
    }
];